---
monitor_state: present
ring_monitor_name: Health_HTTP_RING
ring_monitor_parent: /Common/http
ring_monitor_send: "GET /_/healthcheck/deep HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n"
ring_monitor_receive: "HTTP/1.1 200 OK"
